#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# ──────────────────────────────────────────────────────────────────────────
# STAGES
#
# Monta o ambiente de HOMOLOGACAO do IM-Calculo: copia o banco de producao pro
# projeto "Calculo IM Homologacao", anonimiza o que e PII, publica as edge
# functions de acesso e sobe um site proprio no Vercel pra controladoria testar
# sem tocar em producao.
#
# Idempotente por estagio: da pra parar no meio (Ctrl-C) e rodar de novo.
# O unico estagio destrutivo (3) pergunta antes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

PROD_REF="jdkkusrxullttyeakwib"      # Calculo IM (PRODUCAO)
HOMOLOG_REF="ibscxvkgrdyzlgtgbbuz"   # Calculo IM Homologacao
DUMP_DIR="docs/homolog"

# .env.homolog e um arquivo do Vite (VITE_*), lido pelo BROWSER.
# Nunca gravar connection string nem senha de banco aqui.
ENV_FILE=".env.homolog"

# ── helpers locais ────────────────────────────────────────────────────────

# pg_env REF SENHA exporta PG* apontando pro projeto. Usamos o SESSION POOLER
# (porta 5432) e nao o host direto: conexao direta no Supabase e IPv6-only e
# falha na maioria das redes domesticas/corporativas.
pg_env() {
  export PGHOST="$POOLER_HOST" PGPORT="5432" PGDATABASE="postgres"
  export PGUSER="postgres.$1" PGPASSWORD="$2"
}

# psql_h roda um comando no HOMOLOG e devolve so o valor (sem cabecalho).
psql_h() { pg_env "$HOMOLOG_REF" "$SENHA_DB_HOMOLOG"; psql -tAX -c "$1"; }

banner "Homologacao do IM-Calculo"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Ferramentas locais (pg_dump + psql)"
say "O clone e feito com pg_dump/psql diretos, nao com 'supabase db dump'."
note "Motivo: o CLI da Supabase roda o pg_dump DENTRO de um container Docker."
note "Sem Docker instalado ele nao funciona — e com o client do Postgres"
note "instalado o Docker deixa de ser necessario pra qualquer passo daqui."

if command -v pg_dump >/dev/null 2>&1 && command -v psql >/dev/null 2>&1; then
  say "Encontrados: $(pg_dump --version | head -1)"
else
  warn "pg_dump/psql nao estao no PATH."
  if command -v winget >/dev/null 2>&1; then
    say "Da pra instalar agora pelo winget (baixa ~300 MB)."
    note "Instala o Postgres completo; o SERVICO pode ficar parado — so"
    note "precisamos das ferramentas de linha de comando."
    if confirm "Instalar o PostgreSQL 17 agora?"; then
      winget install -e --id PostgreSQL.PostgreSQL.17 \
        --accept-package-agreements --accept-source-agreements ||
        warn "winget retornou erro; instale manualmente e rode o wizard de novo."
    fi
  else
    say "Baixe em https://www.postgresql.org/download/ (marque 'Command Line Tools')."
  fi
  # O instalador nem sempre poe o bin no PATH da sessao atual.
  for d in "/c/Program Files/PostgreSQL"/*/bin; do
    [[ -d "$d" ]] && export PATH="$PATH:$d"
  done
  if ! command -v pg_dump >/dev/null 2>&1; then
    warn "Ainda nao achei o pg_dump. Feche e reabra o terminal e rode de novo."
    exit 1
  fi
  say "Agora sim: $(pg_dump --version | head -1)"
fi
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Credenciais dos dois bancos"
say "Precisamos da senha do banco de cada projeto e do host do pooler."
warn "As senhas ficam so na memoria deste script. Nada e gravado em arquivo."

open_url "https://supabase.com/dashboard/project/$HOMOLOG_REF/settings/database"
step "Em Connection string, escolha a aba 'Session pooler' e copie a URI."
note "Tem a forma postgresql://postgres.<ref>:[SENHA]@<host-do-pooler>:5432/postgres"
ask POOLER_URI "Cole a URI do pooler (do HOMOLOGACAO):"
POOLER_HOST=$(printf '%s' "$POOLER_URI" | sed -E 's#.*@([^:/]+).*#\1#')
if [[ -z "$POOLER_HOST" || "$POOLER_HOST" == "$POOLER_URI" ]]; then
  warn "Nao consegui ler o host da URI."
  ask POOLER_HOST "Digite so o host (ex.: aws-0-us-east-1.pooler.supabase.com):"
fi
say "Host do pooler: $POOLER_HOST"
note "Os dois projetos estao em us-east-1, entao compartilham o mesmo pooler."

step "Se nao lembra a senha do banco do HOMOLOGACAO, use 'Reset database password'."
ask_secret SENHA_DB_HOMOLOG "Senha do banco de HOMOLOGACAO:"

open_url "https://supabase.com/dashboard/project/$PROD_REF/settings/database"
step "Mesma pagina, agora no projeto de PRODUCAO. Copie ou redefina a senha."
warn "Producao so sera LIDA (pg_dump). Nada e escrito la."
ask_secret SENHA_DB_PROD "Senha do banco de PRODUCAO:"

say "Testando as duas conexoes..."
pg_env "$PROD_REF" "$SENHA_DB_PROD"
psql -tAX -c "select 'producao ok: '||count(*)||' vendas' from vendas" || {
  warn "Nao conectei na producao. Confira a senha e o host."
  exit 1
}
pg_env "$HOMOLOG_REF" "$SENHA_DB_HOMOLOG"
psql -tAX -c "select 'homologacao ok'" || {
  warn "Nao conectei na homologacao."
  exit 1
}

say ""
step "Agora a senha UNICA que todos os logins de homologacao vao usar."
note "Toda conta clonada (admin, corretor, cliente) passa a entrar com ela."
note "Escolha algo simples de ditar pra controladoria. Minimo 6 caracteres."
ask_secret SENHA_HOMOLOG "Senha de acesso do ambiente de homologacao:"
[[ ${#SENHA_HOMOLOG} -ge 6 ]] || {
  warn "Senha curta demais."
  exit 1
}
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Copiar producao -> homologacao"
EXISTENTES=$(psql_h "select count(*) from information_schema.tables where table_schema='public'") || {
  warn "Nao consegui consultar a homologacao. Refaca o estagio 2."
  exit 1
}
say "O projeto de homologacao tem $EXISTENTES tabela(s) em public hoje."
if [[ "$EXISTENTES" != "0" ]]; then
  warn "Ja tem conteudo. Recopiar por cima pode conflitar com o que existe."
  note "Pra comecar do zero: Dashboard > Settings > General > Reset database."
fi
say "Vamos gerar dois dumps em $DUMP_DIR/ e restaurar na homologacao."
note "Schema (estrutura, triggers de imutabilidade, functions, policies) e dados."
note "Os dados incluem auth.users e storage — e por isso o estagio 4 existe."
confirm "Escrever no banco de HOMOLOGACAO agora?" || {
  warn "Abortado."
  exit 1
}

mkdir -p "$DUMP_DIR"
pg_env "$PROD_REF" "$SENHA_DB_PROD"

say "1/3 dump do schema..."
pg_dump --schema-only --quote-all-identifier \
  --exclude-schema "information_schema|pg_*|_analytics|_realtime|_supavisor|auth|etl|extensions|pgbouncer|realtime|storage|supabase_functions|supabase_migrations|cron|dbdev|graphql|graphql_public|net|pgmq|pgsodium|pgsodium_masks|pgtle|repack|tiger|tiger_data|timescaledb_*|_timescaledb_*|topology|vault" |
  sed -E 's/^CREATE SCHEMA "/CREATE SCHEMA IF NOT EXISTS "/' |
  sed -E 's/^CREATE TABLE "/CREATE TABLE IF NOT EXISTS "/' |
  sed -E 's/^CREATE SEQUENCE "/CREATE SEQUENCE IF NOT EXISTS "/' |
  sed -E 's/^CREATE VIEW "/CREATE OR REPLACE VIEW "/' |
  sed -E 's/^CREATE FUNCTION "/CREATE OR REPLACE FUNCTION "/' |
  sed -E 's/^CREATE TRIGGER "/CREATE OR REPLACE TRIGGER "/' |
  sed -E 's/^(CREATE|ALTER) EVENT TRIGGER /-- &/' |
  sed -E 's/^(CREATE|ALTER) PUBLICATION "supabase_realtime/-- &/' |
  sed -E 's/^COMMENT ON EXTENSION /-- &/' \
  >"$DUMP_DIR/schema.sql" || {
  warn "pg_dump do schema falhou (veja o erro acima)."
  exit 1
}
say "   $(wc -l <"$DUMP_DIR/schema.sql") linhas"

say "2/3 dump dos dados (tabelas backup_* ficam de fora)..."
{
  # replica: nao dispara os triggers de imutabilidade (017/018) durante a carga
  echo "SET session_replication_role = replica;"
  pg_dump --data-only --quote-all-identifier \
    --exclude-schema "information_schema|pg_*|graphql|graphql_public|pgsodium|pgsodium_masks|pgtle|repack|tiger|tiger_data|topology|vault|etl|extensions|pgbouncer|realtime|supabase_migrations|_analytics|_realtime|_supavisor" \
    --exclude-table "auth.schema_migrations" \
    --exclude-table "storage.migrations" \
    --exclude-table "supabase_functions.migrations" \
    --exclude-table "public.backup_*" \
    --schema "*"
  echo "RESET ALL;"
} >"$DUMP_DIR/dados.sql" || {
  warn "pg_dump dos dados falhou (veja o erro acima)."
  exit 1
}
say "   $(wc -l <"$DUMP_DIR/dados.sql") linhas"

say "3/3 restaurando na homologacao..."
pg_env "$HOMOLOG_REF" "$SENHA_DB_HOMOLOG"
psql -v ON_ERROR_STOP=1 -f "$DUMP_DIR/schema.sql" >/dev/null || {
  warn "Falhou no schema. O log acima diz onde."
  exit 1
}
psql -v ON_ERROR_STOP=1 -f "$DUMP_DIR/dados.sql" >/dev/null || {
  warn "Falhou nos dados."
  note "Causa mais provavel: o projeto de homologacao e mais novo que o de"
  note "producao e o auth.users de la ganhou colunas. Nesse caso repita o dump"
  note "de dados incluindo auth no --exclude-schema e crie os logins na mao."
  exit 1
}
say "Copiado."
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Anonimizar (o passo que nao pode ser pulado)"
say "O clone trouxe dado pessoal de verdade. Vamos mascarar antes de qualquer"
say "pessoa abrir a tela:"
step "clientes/leads: nome, CPF, RG, e-mail, telefone, endereco, URLs de documento"
step "auth: senha de todo mundo vira a senha unica, e-mail vira @homolog.local"
step "storage.objects: apagado (os arquivos nao vieram no clone, so as linhas)"
note "PRESERVA de proposito: nome de corretor e coordenadora (a controladoria"
note "precisa reconhecer os casos), e TODO valor, data, unidade e fator."

psql_h "create table if not exists public._homolog_marker (criado_em timestamptz default now());" >/dev/null || {
  warn "Nao consegui criar a marca de homologacao."
  exit 1
}
say "Marca de homologacao criada (o anonimizador se recusa a rodar sem ela)."

pg_env "$HOMOLOG_REF" "$SENHA_DB_HOMOLOG"
psql -v ON_ERROR_STOP=1 -f scripts/homolog/anonimizar.sql || {
  warn "Falhou ao anonimizar o schema public."
  exit 1
}
psql -v ON_ERROR_STOP=1 -v senha="$SENHA_HOMOLOG" -f scripts/homolog/anonimizar-auth.sql || {
  warn "Falhou ao anonimizar auth/storage."
  exit 1
}

say ""
say "Conferindo se sobrou PII:"
psql -X -c "select
    (select count(*) from clientes where nome_completo not like 'CLIENTE TESTE%') as clientes_com_nome_real,
    (select count(*) from auth.users where email not like '%@homolog.local')      as logins_com_email_real,
    (select count(*) from storage.objects)                                        as arquivos_orfaos"
warn "Os tres numeros acima precisam ser 0. Se nao forem, PARE aqui."
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Edge functions no projeto de homologacao"
say "Sem isto, o botao de criar acesso no Admin nao funciona la: ele chama uma"
say "edge function, e o deploy automatico do repo so publica na producao."
note "Vamos publicar SO as duas de acesso."
note "sienge-sync fica de fora de proposito: se rodar, sobrescreve o snapshot"
note "que a controladoria esta testando. Boletos ficam de fora pra nao existir"
note "nenhum caminho ate uma cobranca real."

open_url "https://supabase.com/dashboard/account/tokens"
step "Gere um Personal Access Token (ou reuse um) e copie."
ask_secret SUPABASE_ACCESS_TOKEN "Cole o access token:"
export SUPABASE_ACCESS_TOKEN

for fn in admin-corretor-acesso admin-cliente-acesso; do
  say "publicando $fn..."
  # --no-verify-jwt: o preflight OPTIONS do browser nao leva Authorization;
  # a autenticacao (JWT + tipo='admin') e feita dentro da propria funcao.
  npx -y supabase@latest functions deploy "$fn" \
    --project-ref "$HOMOLOG_REF" --no-verify-jwt || {
    SKIPPED+=("deploy da edge function $fn")
    warn "falhou; da pra repetir depois"
  }
done
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Site de homologacao no Vercel"
say "A controladoria precisa de um endereco proprio pra abrir — o mesmo codigo,"
say "apontando pro banco de homologacao."
note "Projeto extra no Vercel nao tem custo proprio: a cobranca e por assento e"
note "por uso, com cota compartilhada. Um site interno consome quase nada."

[[ -f "$ENV_FILE" ]] || cp .env.homolog.example "$ENV_FILE"
open_url "https://supabase.com/dashboard/project/$HOMOLOG_REF/settings/api-keys"
step "Copie a chave publica (anon / publishable) do projeto de homologacao."
ask VITE_SUPABASE_URL "URL do Supabase de homologacao:"
ask VITE_SUPABASE_ANON_KEY "Chave publica (anon):"
write_env VITE_SUPABASE_URL "$VITE_SUPABASE_URL"
write_env VITE_SUPABASE_ANON_KEY "$VITE_SUPABASE_ANON_KEY"
note "Com isso ja da pra testar local: npm run dev -- --mode homolog"

open_url "https://vercel.com/new"
step "Importe o MESMO repositorio (Neskrux/IM-Calculo) como um projeto NOVO."
step "De o nome 'im-calculo-homolog' (vira im-calculo-homolog.vercel.app)."
step "Em Environment Variables, adicione as duas abaixo, em todos os ambientes:"
say "    VITE_SUPABASE_URL      = $VITE_SUPABASE_URL"
say "    VITE_SUPABASE_ANON_KEY = (a chave que voce acabou de colar)"
warn "Confira que sao as de HOMOLOGACAO. Colar as de producao aqui faz a"
warn "controladoria testar em cima do banco real sem perceber."
step "Deploy."
ask HOMOLOG_APP_URL "Cole o endereco final do site de homologacao:"
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Conferir e entregar"
say "Os logins do ambiente (todos com a senha unica que voce definiu):"
pg_env "$HOMOLOG_REF" "$SENHA_DB_HOMOLOG"
psql -X -c "select p.tipo, coalesce(p.cargo_beneficiario,'') as cargo, p.nome, u.email as login
            from public.usuarios p join auth.users u on u.id = p.id
            where p.tipo in ('admin','beneficiario')
               or p.nome ilike '%caroline%' or p.nome ilike '%jessica%'
               or p.nome ilike '%matheus%'
            order by p.tipo, p.nome"
note "Qualquer outro login sai com:"
note "  select p.nome, u.email from usuarios p join auth.users u on u.id=p.id"
note "  where p.nome ilike '%<parte do nome>%';"

say ""
step "Abra o site, entre com o login de admin e confira:"
step "  - os totais batem com o que voce ve em producao"
step "  - os nomes de cliente aparecem como 'CLIENTE TESTE ...'"
step "  - os nomes de corretor continuam legiveis"
[[ -n "${HOMOLOG_APP_URL:-}" ]] && open_url "$HOMOLOG_APP_URL"
pause

SKIPPED+=("apagar os dumps locais: rm -rf $DUMP_DIR (contem os dados REAIS de producao)")
SKIPPED+=("mandar pra controladoria: endereco ${HOMOLOG_APP_URL:-<url>} + login + a senha unica")

finish
